# Generated by Django 4.2.5 on 2023-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
